language: rust
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - libasound2-dev
      - libudev-dev
      - libssl-dev
env:
  global:
    - RUST_BACKTRACE=1
  matrix:
    - WASM=0
rust:
  - stable
  - beta
  - nightly
matrix:
  include:
    - rust: nightly
      env: WASM=0
      script:
        - cargo check --examples --no-default-features
    - rust: nightly
      env: WASM=1
      install: rustup target add wasm32-unknown-unknown
      script:
        - cargo +nightly check --target wasm32-unknown-unknown --examples
    - rust: nightly
      env: WASM=1
      install: rustup target add wasm32-unknown-unknown
      script:
        - cargo +nightly check --target wasm32-unknown-unknown --examples --no-default-features
after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == "stable" && "$TRAVIS_OS_NAME" == "linux"]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin 
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi
  allow_failures:
    - rust: nightly
      env: WASM=0
  fast_finish: true
