[package]
name = "quicksilver"
description = "A simple game framework for 2D games in pure Rust"
version = "0.3.19"
authors = ["Ryan Goldstein <ryanisaacg@gmail.com>"]
categories = ["game-engines"]
homepage = "https://ryanisaacg.github.io/quicksilver"
keywords = ["game", "audio", "graphics", "gamedev"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/ryanisaacg/quicksilver"
exclude = ["docs/*"]
edition = "2018"

[features]
# complex_shapes, fonts, gamepads, sounds
default = ["saving"]

# fonts = ["rusttype"]
# gamepads = ["gilrs"]
saving = ["gestalt"]
# sounds = ["rodio"]
std_web = ["gestalt/stdweb", "platter/stdweb", "blinds/stdweb", "golem/stdweb"]
web-sys = ["gestalt/web-sys", "platter/web-sys", "blinds/web-sys", "golem/web-sys"]

[badges]

travis-ci = { repository = "ryanisaacg/quicksilver", branch = "master" }
maintenance = { status = "actively-developed" }

[dependencies]
gestalt = { version = "0.1", optional = true }
golem = { git = "https://github.com/ryanisaacg/golem" }
image = "0.21"
mint = "0.5.3"
platter = "0.1"
blinds = { version = "0.1.0-alpha2", features = ["gl"] }
vek = { version = "0.9.10", features = ["mint"] }

