[package]
name = "quicksilver"
description = "A simple game framework for 2D games in pure Rust"
version = "0.1.1"
authors = ["Ryan Goldstein <ryanisaacg@gmail.com>"]
repository = "https://github.com/ryanisaacg/quicksilver"
readme = "README.md"
license = "MIT/Apache-2.0"
keywords = ["game", "audio", "graphics", "gamedev"]
categories = ["game-engines"]

[features]
default = ["fonts", "gamepads", "geometry", "collision", "window", "saving", "sounds"]

fonts = ["window", "rusttype"]
gamepads = ["gilrs", "window"]
geometry = ["rand", "serde", "serde_derive"]
collision = ["alga", "nalgebra", "ncollide"]
window = ["geometry", "gl", "glutin", "image", "futures", "rusttype"]
saving = ["serde", "serde_json"]
sounds = ["futures", "rodio"]

[badges]

travis-ci = { repository = "ryanisaacg/quicksilver", branch = "master" }
maintenance = { status = "actively-developed" }

[dependencies]
alga = { version = "0.5", optional = true }
futures = { version = "0.1", optional = true }
gl = { version = "0.10", optional = true }
nalgebra = { version = "0.14", optional = true }
ncollide = { version = "0.14", optional = true }
rand = { version = "0.4.2", optional = true }
rusttype = { version = "0.3", optional = true }
serde = { version = "1.0", optional = true }
serde_derive = { version = "1.0", optional = true }
serde_json = { version = "1.0", optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
glutin = { version = "0.12.2", optional = true }
gilrs = { version = "0.6", optional = true }
image = { version = "0.18", optional = true }
rodio = { version = "0.6", optional = true }

[[example]]
name = "basic"
required-features = ["window"]

[[example]]
name = "draw-geometry"
required-features = ["geometry", "window"]

[[example]]
name = "pulsing-circle"
required-features = ["geometry", "window"]

[[example]]
name = "platformer"
required-features = ["geometry", "window", "gamepads"]

[[example]]
name = "image"
required-features = ["window"]

[[example]]
name = "font"
required-features = ["window", "fonts"]

[[example]]
name = "sound"
required-features = ["geometry", "window", "sounds"]

[[example]]
name = "meteors"
required-features = ["geometry", "window"]
