[package]
name = "quicksilver"
description = "A simple game framework for 2D games in pure Rust"
version = "0.1.1"
authors = ["Ryan Goldstein <ryanisaacg@gmail.com>"]
categories = ["game-engines"]
homepage = "https://ryanisaacg.github.io/quicksilver"
keywords = ["game", "audio", "graphics", "gamedev"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/ryanisaacg/quicksilver"

[features]
default = ["collisions", "fonts", "gamepads", "saving", "sounds"]

collisions = ["alga", "nalgebra", "ncollide2d"]
fonts = ["rusttype"]
gamepads = ["gilrs"]
saving = ["serde_json"]
sounds = ["rodio"]

[badges]

travis-ci = { repository = "ryanisaacg/quicksilver", branch = "master" }
maintenance = { status = "actively-developed" }

[dependencies]
futures = "0.1"
gl = "0.10"
rand = "0.5"
serde = "1.0"
serde_derive = "1.0"
alga = { version = "0.5", optional = true }
nalgebra = { version = "0.14", optional = true }
ncollide2d = { version = "0.15", optional = true }
rusttype = { version = "0.6", optional = true }
serde_json = { version = "1.0", optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
glutin = "0.12"
image = "0.18"
gilrs = { version = "0.6", optional = true }
rodio = { version = "0.7", optional = true }

[[example]]
name = "basic"
required-features = []

[[example]]
name = "draw-geometry"
required-features = []

[[example]]
name = "pulsing-circle"
required-features = []

[[example]]
name = "image"
required-features = []

[[example]]
name = "font"
required-features = ["fonts"]

[[example]]
name = "sound"
required-features = ["sounds"]

[[example]]
name = "raycast"
required-features = ["collisions"]

